from .employees.employee_list import employee_list
from .employees.employee_details import employee_details
from .departments.department_list import department_list
from .departments.department_form import department_form
from .departments.department_details import department_details
from .training_programs.training_program_list import training_program_list
from .training_programs.form import training_program_form
from .computers.comp_list import computer_list
from .computers.comp_details import computer_details
from .home import home
from .auth.logout import logout_user
from .employees.employee_form import employee_form
